### ISSUE TITLE
not a issue just a warning ;)

### ISSUE THREAD

**Issue by gcmartijn** [Regal-Internet-Brothers/deltatime#1]
I get this warning inside the debugger.
game.buildv85b/glfw3/main.cpp:14774:8: warning: unused variable 't_Delta' [-Wunused-variable]
        Float t_Delta=m_DeltaTime->m_Delta;
              ^
game.buildv85b/glfw3/main.cpp:14826:8: warning: unused variable 't_Delta' [-Wunused-variable]
        Float t_Delta=m_DeltaTime->m_Delta;
              ^
2 warnings generated.

**Comment by ImmutableOctet** [comment]
o_O? - You've got good intentions, but it would only be unused if you're not using any code that references 'Delta'. 'Delta' is used in several methods, but it's not going to be referenced in the native code without calling them. **That being said, the "t" prefix is for local variables, "m" is for normal fields.** Following that logic, you probably have an unused variable named 'Delta'. Unless it's in my code, which is still possible.

Thanks for taking the time, though.

**Comment by gcmartijn** [comment]
Learned something new now, thanks ;)
It was indeed nog using the Local Delta created inside a basic template.
I was starting a new game, based on your delta code here:
http://www.monkey-x.com/Community/posts.php?topic=10074
